name: CI REST API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies for linting
        run: |
          pip install poetry
          poetry install
      - name: Run linters
        run: |
          poetry run black --check .
          poetry run flake8
          poetry run isort --check-only .

  test:
    name: Testing API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies for tests
        run: |
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run python manage.py test
